### ISSUE TITLE
Load commands palette triggers the modal

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/Obsidian-ZettlelFlow#16]
When I click on the sidebar icon, an empty window appears.

<img width="458" alt="image" src="https://github.com/RafaelGB/Obsidian-ZettlelFlow/assets/7627504/db77b9d8-f3ba-43f0-b182-fe6fb381cf6a">

When the plugin is activated when accessing the command palette the same thing happens.

<img width="513" alt="image" src="https://github.com/RafaelGB/Obsidian-ZettlelFlow/assets/7627504/020202b0-82b3-4d70-9b7c-0139bfc22734">

SYSTEM INFO:
	Obsidian version: v1.4.5
	Installer version: v1.3.5
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.2.1
	Snippets enabled: 16
	Restricted mode: off
	Plugins installed: 192
	Plugins enabled: 4
		1: Dataview v0.5.56
		2: Style Settings v1.0.6
		3: ZettelFlow v0.0.3
		4: Minimal Theme Settings v7.2.2

**Comment by javiavid** [comment]
When changing the configuration it no longer appears empty, but the plugin continues to open when I load the command palette CTRL+P.

<img width="512" alt="image" src="https://github.com/RafaelGB/Obsidian-ZettlelFlow/assets/7627504/066cb9ab-b8d8-4d73-b981-d38ce78df69b">

**Comment by RafaelGB** [comment]
I will check the reason of this behaviour, thanks a lot for the report!

**Comment by RafaelGB** [comment]
was a quickFix!

I was picking checkingCallback instead of callback option for the command. Fixed with the next version
